language: node_js
os:
- linux
- osx
node_js:
- '8'
install:
- travis_retry npm install -g esy@0.2.9
- travis_wait travis_retry make bootstrap
script:
- esy install
- esy build
cache:
  timeout: 360
  directories:
  - "$HOME/.esy/"
